name = "google-sheets-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "google-sheets-mcp-prod"

[env.staging]
name = "google-sheets-mcp-staging"

# Environment variables (set via wrangler secret put)
# GOOGLE_SERVICE_ACCOUNT_KEY - JSON string of service account credentials
# QUICKBOOKS_CLIENT_ID - QuickBooks app client ID
# QUICKBOOKS_CLIENT_SECRET - QuickBooks app client secret
# ALLOWED_ORIGINS - Comma-separated list of allowed origins for CORS

[vars]
NODE_ENV = "production"
MCP_VERSION = "1.1.0"
DEFAULT_SPREADSHEET_ID = "1sXrmr0GlfKMk6TicjEuLaV22_-j7M_5TEBjy7OvcnwE"

# Node.js compatibility for Google APIs
node_compat = true 